package problem12

import (
	"math"
)

/**
 * Highly divisible triangular number
 *
 * https://projecteuler.net/problem=12
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *     1: 1
 *     3: 1,3
 *     6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * http://odz.sakura.ne.jp/projecteuler/index.php?cmd=read&page=Problem%2012
 * 三角数の数列は自然数の和で表わされ, 7番目の三角数は 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28 である. 三角数の最初の10項は:
 *   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * となる.
 * 最初の7項について, その約数を列挙すると, 以下のとおり.
 *     1: 1
 *     3: 1,3
 *     6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 * これから, 7番目の三角数である28は, 5個より多く約数をもつ最初の三角数であることが分かる.
 * では, 500個より多く約数をもつ最初の三角数はいくつか.
 *
 * Contents of Project Euler are licenced under a Creative Commons Licence: Attribution-NonCommercial-ShareAlike 2.0 UK: England & Wales.
 * http://creativecommons.org/licenses/by-nc-sa/2.0/uk/
 */

//Answer0 returns answer to this problem
func Answer0(limit int64) int64 {
	if limit == 0 {
		return 1
	}
	cancel := make(chan struct{}, 1)
	ch := genTriangularNumber(cancel)
	defer func() {
		cancel <- struct{}{}
		<-ch
	}()
	var tn int64 = 0
	for n := range ch {
		//fmt.Println(n)
		rn := int64(math.Sqrt(float64(n)))
		ct := int64(0)
		for i := int64(1); i <= rn; i++ {
			if n%i == 0 {
				ct += 2
			}
		}
		if rn*rn == n {
			ct--
		}
		if ct > limit {
			tn = n
			break
		}
	}
	return tn
}
func genTriangularNumber(cancel <-chan struct{}) <-chan int64 {
	ch := make(chan int64)
	go func() {
		defer close(ch)
		tn := int64(0)
		for n := int64(1); ; n++ {
			select {
			case <-cancel:
				return
			default:
				tn += n
				ch <- tn
			}
		}
	}()
	return ch
}

//Answer1 returns answer to this problem (refactoring version)
func Answer1(limit int64) int64 {
	//primes := getPrimes(1000)
	for n := int64(1); ; n++ {
		tn := n * (n + 1) / 2
		//fmt.Println("tn =", tn)
		ct := int64(1)
		ttn := tn
		for _, p := range primes {
			if p*p > tn {
				ct *= 2
				break
			}
			exp := int64(0)
			for ; ttn%p == 0; ttn /= p {
				exp++
			}
			if exp > 0 {
				//fmt.Printf("P =%v^%v\n", p, exp)
				ct *= exp + 1
			}

		}
		if ct > limit {
			return tn
		}
	}
}

var primes = getPrimes(1000)

//getPrimes is the Sieve of Eratosthenes
func getPrimes(limit int64) []int64 {
	sievebound := (limit - 1) / 2
	sieve := make([]bool, sievebound+1)
	sieve[0] = true
	for i := int64(1); i <= sievebound; i++ {
		sieve[i] = false
	}
	crosslimit := (int64(math.Sqrt(float64(limit))) - 1) / 2

	for i := int64(1); i <= crosslimit; i++ {
		if !sieve[i] { // 2*i+1 is prime, and mark multiples
			for j := 2 * i * (i + 1); j <= sievebound; j += 2*i + 1 {
				sieve[j] = true
			}
		}
	}
	primes := []int64{2}
	for i, sv := range sieve {
		if !sv {
			primes = append(primes, 2*int64(i)+1)
		}
	}
	return primes
}

/* Copyright 2018 Spiegel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
